### PR TITLE
Allow passing the gfx directory as a command line argument

### PR DESCRIPTION
**Pull request by coolreader18**
This would allow for much easier packaging for e.g. the AUR.

### CODE REVIEW

**Comment by coolreader18** [comment]
I've added sm64plus to the AUR: https://aur.archlinux.org/packages/sm64plus-git/

**Comment by MorsGames** [comment]
Awesome! I'll be checking this out later today and will merge if there are no issues.

**Comment by coolreader18** [comment]
Cool, thanks! It would also be really helpful for packaging if you kept like a `VERSION` file that just has the current version in it, or at least just keeping the format of the changelog entries the same would also work. (I get the version by doing `cat README.md | grep -Po '### v\K[0-9\.]+' | head -n1`)

**Comment by MorsGames** [comment]
Sure thing!

**Comment by MorsGames** [comment]
It seems like I completely forgot about adding that VERSION file WHOOPS!

Sorry about that, it should be now added in as well.

**Comment by coolreader18** [comment]
Awesome, thanks!

**Pull request merged**
