### PR TITLE
Coyote Frames Mechanic

### PR DESCRIPTION
**Pull request by Kodiak-Web**
Adds a mechanic in which you can jump in the freefall action for a configurable amount of frames after leaving the ground and an entry in the launcher and related config files under gameplay, though you'll likely want to move it to another category, i'm just not sure which

### CODE REVIEW

**Comment by Kodiak-Web** [comment]
how do i edit my own pull request

**Review by MorsGames — CHANGES_REQUESTED** [review]
You're missing the config entry in the categories.json file. In addition I think controls would be a better place for this, yeah.

Otherwise, it looks good!

**Comment by Kodiak-Web** [comment]
i cant figure out how to get the launcher entry working right

**Comment by Kodiak-Web** [comment]
it defaults to -1 and crashes always, how can i fix that

**Comment by Kodiak-Web** [comment]
or its absurdly large

**Comment by Kodiak-Web** [comment]
image

**Pull request closed without merging**
